nelmio_api_doc:
  documentation:
      info:
        title: Bantu-dico Official API dev
        description: French - Lingala - Sango Dictionary
        version: 1.0.0
  areas:
    path_patterns: # an array of regexps
      - ^/api(?!/doc$)
